
puts "Creating Parties"

Party.create!(id: 'T35C', name: "30-50 Coalition")
Party.create!(id: 'AB', name: "Above and Beyond")
Party.create!(id: 'AZNO', name: "Al-Zebabist Nation of Ooog")
Party.create!(id: 'APPL', name: "All People's Party")
Party.create!(id: 'AGS', name: "Alliance for Green Socialism")
Party.create!(id: 'ALL', name: "Alliance Party")
Party.create!(id: 'ALC', name: "Alter Change")
Party.create!(id: 'ANWP', name: "Animal Welfare Party")
Party.create!(id: 'APNI', name: "Apni Party")
Party.create!(id: 'AD', name: "Apolitical Democrats")
Party.create!(id: 'BEER', name: "Beer, Baccy and Scratchings")
Party.create!(id: 'TBP', name: "Birthday Party")
Party.create!(id: 'BIA', name: "Bournemouth Independent Alliance")
Party.create!(id: 'BD', name: "British Democrats")
Party.create!(id: 'BI', name: "British Independents")
Party.create!(id: 'BNP', name: "British National Party")
Party.create!(id: 'CAM', name: "Campaign")
Party.create!(id: 'CSA', name: "Cannabis is Safer than Alcohol")
Party.create!(id: 'COTA', name: "Children of the Atom")
Party.create!(id: 'CHM', name: "Christian Movement for Great Britain")
Party.create!(id: 'CHP', name: "Christian Party")
Party.create!(id: 'CPA', name: "Christian Peoples Alliance")
Party.create!(id: 'CFU', name: "Citizens for Uttlesford")
Party.create!(id: 'CW', name: "Class War")
Party.create!(id: 'CMSP', name: "Common Sense Party")
Party.create!(id: 'COML', name: "Communist League")
Party.create!(id: 'COMP', name: "Communist Party")
Party.create!(id: 'CMU', name: "Communities United Party")
Party.create!(id: 'CON', name: "Conservative Party")
Party.create!(id: 'DEM', name: "Democratic Party")
Party.create!(id: 'DRP', name: "Democratic Reform Party")
Party.create!(id: 'DUP', name: "Democratic Unionist Party")
Party.create!(id: 'DD', name: "Digital Democracy")
Party.create!(id: 'EPGB', name: "Eccentric Party of Great Britain")
Party.create!(id: 'ED', name: "English Democrats")
Party.create!(id: 'EUR', name: "Europeans Party")
Party.create!(id: 'TEP', name: "Evolution Party")
Party.create!(id: 'FPTP', name: "Free Public Transport Party")
Party.create!(id: 'FREE', name: "Free United Kingdom Party")
Party.create!(id: 'GRN', name: "Green Party")
Party.create!(id: 'GGG', name: "Guildford Greenbelt Group")
Party.create!(id: 'HOPO', name: "Hoi Polloi")
Party.create!(id: 'HUM', name: "Humanity")
Party.create!(id: 'IFE', name: "Independence from Europe")
Party.create!(id: 'IND', name: "Independent")
Party.create!(id: 'ICHC', name: "Independent Community and Health Concern")
Party.create!(id: 'IPAP', name: "Independent Political Alliance Party")
Party.create!(id: 'IFB', name: "Independents for Bristol")
Party.create!(id: 'IZB', name: "Islam Zinda Baad Platform")
Party.create!(id: 'JAC', name: "Justice and Anti-Corruption Party")
Party.create!(id: 'JMB', name: "Justice for Men and Boys")
Party.create!(id: 'LAB', name: "Labour Party")
Party.create!(id: 'LP', name: "Land Party")
Party.create!(id: 'LU', name: "Left Unity")
Party.create!(id: 'LCBP', name: "Let Every Child Have Both Parents")
Party.create!(id: 'KIR', name: "Let's Keep it Real")
Party.create!(id: 'LIB', name: "Liberal")
Party.create!(id: 'LD', name: "Liberal Democrat")
Party.create!(id: 'LIGB', name: "Liberty GB")
Party.create!(id: 'LNIN', name: "Lincolnshire Independents")
Party.create!(id: 'LHSC', name: "Locally Informed Health and Social Care")
Party.create!(id: 'MCP', name: "Magna Carta Party")
Party.create!(id: 'MCCP', name: "Magna Carter Conservation Party")
Party.create!(id: 'MAIN', name: "Mainstream")
Party.create!(id: 'MAIP', name: "Manston Airport Independent Party")
Party.create!(id: 'MK', name: "Mebyon Kernow")
Party.create!(id: 'MRLP', name: "Monster Raving Loony Party")
Party.create!(id: 'MAD', name: "Movement for Active Democracy")
Party.create!(id: 'NF', name: "National Front")
Party.create!(id: 'NHSA', name: "National Health Action Party")
Party.create!(id: 'NLP', name: "National Liberal Party")
Party.create!(id: 'NIC', name: "New Independent Centralists")
Party.create!(id: 'NSOW', name: "New Society of Worth")
Party.create!(id: 'NEP', name: "North East Party")
Party.create!(id: 'NORP', name: "Northern Party")
Party.create!(id: 'PUT', name: "Party for a United Thanet")
Party.create!(id: 'PATR', name: "Patria")
Party.create!(id: 'PSP', name: "Patriotic Socialist Party")
Party.create!(id: 'PPNV', name: "Peace Party")
Party.create!(id: 'PBP', name: "People Before Profit")
Party.create!(id: 'PF', name: "People First")
Party.create!(id: 'PILP', name: "Pilgrim Party")
Party.create!(id: 'PIRT', name: "Pirate Party UK")
Party.create!(id: 'PC', name: "Plaid Cymru")
Party.create!(id: 'PLP', name: "Pluralist Party")
Party.create!(id: 'POOL', name: "Poole People")
Party.create!(id: 'PPUK', name: "Population Party UK")
Party.create!(id: 'POPP', name: "Principles of Politics Party")
Party.create!(id: 'PCF', name: "Putting Croydon First")
Party.create!(id: 'TRP', name: "Realists' Party")
Party.create!(id: 'RBD', name: "Rebooting Democracy")
Party.create!(id: 'RFAC', name: "Red Flag - Anti-Corruption")
Party.create!(id: 'RVIS', name: "Reduce VAT in Sport")
Party.create!(id: 'RS', name: "Republican Socialist")
Party.create!(id: 'RES', name: "Respect Party")
Party.create!(id: 'RFP', name: "Rochdale First")
Party.create!(id: 'TRPA', name: "Roman Party")
Party.create!(id: 'SHP', name: "Save Hartlepool Hospital")
Party.create!(id: 'SNP', name: "Scottish National Party")
Party.create!(id: 'SF', name: "Sinn Fein")
Party.create!(id: 'SDLP', name: "Social Democratic and Labour Party")
Party.create!(id: 'SDP', name: "Social Democratic Party")
Party.create!(id: 'SEP', name: "Socialist Equality Party")
Party.create!(id: 'SLP', name: "Socialist Labour Party")
Party.create!(id: 'SOC', name: "Socialist Party")
Party.create!(id: 'SN', name: "Something New")
Party.create!(id: 'TSP', name: "Southport Party")
Party.create!(id: 'SPK', name: "Speaker")
Party.create!(id: 'SECA', name: "Give Me Back Elmo")
Party.create!(id: 'SPP', name: "Sustainable Population Party")
Party.create!(id: 'TPP', name: "The Pluralist Party")
Party.create!(id: 'TUSC', name: "Trade Unionist and Socialist Coalition")
Party.create!(id: 'TUV', name: "Traditional Unionist Voice")
Party.create!(id: 'UP', name: "U Party")
Party.create!(id: 'TUP', name: "Ubuntu Party")
Party.create!(id: 'PDP', name: "UK Progressive Democracy Party")
Party.create!(id: 'UUP', name: "Ulster Unionist Party")
Party.create!(id: 'UKIP', name: "United Kingdom Independence Party")
Party.create!(id: 'VAP', name: "Vapers in Power")
Party.create!(id: 'WVP', name: "War Veteran's Pro-Traditional Family Party")
Party.create!(id: 'WARP', name: "We Are The Reality Party")
Party.create!(id: 'WR', name: "Wessex Regionalist")
Party.create!(id: 'WHIG', name: "Whig Party")
Party.create!(id: 'WGP', name: "Wigan Independent")
Party.create!(id: 'WP', name: "Workers Party")
Party.create!(id: 'WRP', name: "Workers' Revolutionary Party")
Party.create!(id: 'WPTS', name: "World Peace Through Song")
Party.create!(id: 'YF', name: "Yorkshire First")
Party.create!(id: 'YPP', name: "Young People's Party")
Party.create!(id: 'CNSS', name: "Consensus")
Party.create!(id: 'RFCS', name: "Restore the Family For Children's Sake")
Party.create!(id: 'SSP', name: "Scottish Socialist Party")
Party.create!(id: 'ONL', name: "One Love Party")
Party.create!(id: 'IMMP', name: "Immigrants Political Party")
Party.create!(id: 'BUSP', name: "Bus Pass")
Party.create!(id: 'EIP', name: "English Independence Party")
Party.create!(id: 'REST', name: "The Restoration Party")
Party.create!(id: 'UNKN', name: "Unknown")
Party.create!(id: 'SOUT', name: "All The South Party")
Party.create!(id: 'PPBF', name: "Putting the People of Battersea First")
Party.create!(id: 'MPEA', name: "A Vote Against MP Expense Abuse")
Party.create!(id: 'UV', name: "United Voice")
Party.create!(id: 'TRST', name: "Trust")
Party.create!(id: 'IMPT', name: "Impact Party")
Party.create!(id: 'CG', name: "The Common Good")
Party.create!(id: 'AC', name: "Animals Count")
Party.create!(id: 'APP', name: "Animal Protection Party")
Party.create!(id: 'AWL', name: "Alliance for Workers Liberty")
Party.create!(id: 'BB', name: "A Better Britain for All")
Party.create!(id: 'BCD', name: "Buckinghamshire Campaign For Democracy")
Party.create!(id: 'BEAN', name: "New Millennium Bean")
Party.create!(id: 'BEST', name: "The Best of a Bad Bunch")
Party.create!(id: 'BGPV', name: "Blaenau Gwent People's Voice")
Party.create!(id: 'BIB', name: "Bushra Irfan of Blackburn")
Party.create!(id: 'BIC', name: "Bromsgrove Independent Conservative")
Party.create!(id: 'BLUE', name: "Blue Environment Party")
Party.create!(id: 'BPEP', name: "Bus-Pass Elvis Party")
Party.create!(id: 'CIP', name: "Campaign for Independent Politicians")
Party.create!(id: 'CITY', name: "City Independent")
Party.create!(id: 'CNPG', name: "Community Need Before Private Greed")
Party.create!(id: 'CORD', name: "Cornish Democrats")
Party.create!(id: 'C28', name: "Clause 28, Children's Protection Christian Democrats")
Party.create!(id: 'CMSC', name: "Cambridge Socialists")
Party.create!(id: 'CTDP', name: "Cut the Deficit Party")
Party.create!(id: 'CURE', name: "Citizens for Undead Rights and Equality")
Party.create!(id: 'DDP', name: "Direct Democracy Party")
Party.create!(id: 'DLAB', name: "Democratic Labour Party")
Party.create!(id: 'DNAT', name: "Democratic Nationalist")
Party.create!(id: 'EPA', name: "Equal Parenting Alliance")
Party.create!(id: 'FAWG', name: "Fight for an Anti-War Government")
Party.create!(id: 'FDP', name: "Fancy Dress Party")
Party.create!(id: 'FFR', name: "For Freedom and Responsibility")
Party.create!(id: 'GSOT', name: "Get Snouts Out TheTrough")
Party.create!(id: 'IEAC', name: "Independent Ealing Acton Communities Public Services")
Party.create!(id: 'IFED', name: "Independents Federation UK")
Party.create!(id: 'ILEU', name: "Independent Leave The EU Alliance")
Party.create!(id: 'IPT', name: "Independent People Together")
Party.create!(id: 'ISGB', name: "Independent Save Our Green Belt")
Party.create!(id: 'ISQM', name: "Independents to Save Queen Mary's Hospital")
Party.create!(id: 'IUK', name: "Integrity UK")
Party.create!(id: 'IVH', name: "Independent Voice for Halifax")
Party.create!(id: 'JBNF', name: "Jannen Will Put Brent North First")
Party.create!(id: 'JOY', name: "The Joy of Talk")
Party.create!(id: 'JP', name: "Justice Party")
Party.create!(id: 'LAND', name: "Land is Power")
Party.create!(id: 'Libert', name: "Libertarian Party")
Party.create!(id: 'LLPB', name: "Local Liberals People Before Politics Party")
Party.create!(id: 'LTT', name: "Lawfulness Trustworthiness and Transparency")
Party.create!(id: 'MACI', name: "The Macclesfield Independent")
Party.create!(id: 'MEDI', name: "Medway Independent")
Party.create!(id: 'MEP', name: "Middle England Party")
Party.create!(id: 'MIF', name: "Mansfield Independent Forum")
Party.create!(id: 'MRP', name: "Money Reform Party")
Party.create!(id: 'NCDV', name: "No candidate deserves my vote")
Party.create!(id: 'NLIB', name: "National Liberal")
Party.create!(id: 'NEW', name: "The New Party")
Party.create!(id: 'NFP', name: "Nationwide Reform Party")
Party.create!(id: 'NICF', name: "New Independent Conservative Chelsea and Fulham")
Party.create!(id: 'NBOD', name: "Nobody Party")
Party.create!(id: 'NSPS', name: "Northampton - Save Our Public Services")
Party.create!(id: 'PNDP', name: "People's National Democratic Party")
Party.create!(id: 'POET', name: "The True English (Poetry) Party")
Party.create!(id: 'PPE', name: "Peoples Party Essex")
Party.create!(id: 'REFORM', name: "Reform 2000")
Party.create!(id: 'RRG', name: "Radical Reform Group")
Party.create!(id: 'RTBP', name: "Reduce Tax on Beer Party")
Party.create!(id: 'SACL', name: "Scotland Against Crooked Lawyers")
Party.create!(id: 'SOCA', name: "Socialist Alternative Party")
Party.create!(id: 'SCI', name: "The Science Party")
Party.create!(id: 'SIG', name: "Staffordshire Independent Group")
Party.create!(id: 'SJP', name: "Scottish Jacobite Party")
Party.create!(id: 'SKGP', name: "Save King George Hospital")
Party.create!(id: 'SMA', name: "Scrap Members Allowances")
Party.create!(id: 'SMRA', name: "Solihull and Meriden Residents' Association")
Party.create!(id: 'TF', name: "Tendring First")
Party.create!(id: 'TOC', name: "Tamsin Omond to the Commons")
Party.create!(id: 'UCUNF', name: "UCUNF UUP and CON joint party")
Party.create!(id: 'UPS', name: "Unity for Peace and Socialism")
Party.create!(id: 'VCCA', name: "Virtue Currency Cognitive Appraisal Party")
Party.create!(id: 'VOTE', name: "Go Mad and Vote For Yourself Party")
Party.create!(id: 'AWP', name: "Anticapitalists -Workers' Power")
Party.create!(id: 'YOU', name: "You Party")
Party.create!(id: 'YOUT', name: "Youth Party")
Party.create!(id: 'YRDPL', name: "Your Right to Democracy Party Limited")
